# Generated by Django 2.0.7 on 2018-07-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosp', models.CharField(max_length=50)),
                ('slot', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('modifier', models.CharField(max_length=50)),
                ('cclass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartyp', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('health', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('legs', models.CharField(max_length=50)),
                ('onehand', models.CharField(max_length=50)),
                ('twohand', models.CharField(max_length=50)),
                ('small', models.CharField(max_length=50)),
            ],
        ),
    ]
